### ISSUE TITLE
What's your email?

### ISSUE THREAD

**Issue by allowthere** [lineageos4microg/l4m_website#1]
Your website says:

>Can you add support for my device? It is officially supported by LineageOS
>Yes, no problem, send us an email.

What's microg's email?

-----------------

PS. Can we get d2att please?

**Comment by alterechtschreibung** [comment]
Can you add support for Samsung Galaxy S7 Edge

**Comment by corna** [comment]
@allowthere We're setting up an XDA thread for the devices requests, I'll let you know when it's ready

@alterechtschreibung Yes, if it's supported by official LOS. Ask for it in the XDA thread when it's ready

**Comment by MichaelRupertDev** [comment]
Nextbit Robin has support from LOS, could you add that as well?

Thanks!

**Comment by corna** [comment]
You can find the XDA thrad [here](https://forum.xda-developers.com/android/software/lineageos-microg-t3700997). I've added your devices to the list.
