### ISSUE TITLE
Liberapay

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/l4m_website#10]
Seeing you now have a donation button, I wanted to suggest another donation method. https://liberapay.com/

It is easy to use and the advantage is you get reoccuring donations. One can pay via bank transfer etc.
And LiberaPay is especially made for FLOSS projects, itself being a non-profit.

**Comment by corna** [comment]
We don't take donations, we just forward them to microG (while we cooperate, we're not in direct contact with microG and we don't receive their donations). You should forward this suggestion directly to microG.

**Comment by rugk** [comment]
Ah, I thought you were one team? So you are two teams?

**Comment by corna** [comment]
Yep, we support each other but we don't interact directly.
