### ISSUE TITLE
contact information is missing

### ISSUE THREAD

**Issue by thomas-mc-work** [lineageos4microg/l4m_website#11]
Currently there is no link to a bug tracker or something similar for users to give feedback. I think this should be added to help the users to get in touch.

**Comment by Lanchon** [comment]
absolutely, a "reporting bugs" section is needed. it should direct bugs of l4m website, l4m builds, microg, lineage, etc to the different github bug trackers and/or XDA threads. consider creating empty project(s) in lineageos4microg to use their bugtrackers.

**Comment by corna** [comment]
Done
