### ISSUE TITLE
LineageOS 15.1 + dumpling

### ISSUE THREAD

**Issue by ArchangeGabriel** [lineageos4microg/l4m_website#13]
Hi,

Not sure whether this is the right place for this, but LineageOS 15.1 has started to be released on some devices (well currently experimental builds only, but nightlies are on their way for this night), so I was wondering whether the switch will be made here too for relevant devices.

Also, dumpling (OnePlus 5T) has been made available in LineageOS (15.1 only), will that device appears here anytime soon?

Regards.

**Comment by Lanchon** [comment]
here patiently waiting for dumpling builds to switch to my brand new lava red OP5T :)

btw, do you guys have a LAOS 15.1-supported device to test l4m 15.1 builds? i can test dumpling for you.

**Comment by corna** [comment]
LineageOS for microG 15.1 is almost ready, we'll publish the builds in a couple of days at most.

**Comment by DissCent** [comment]
Thank you :)

**Comment by corna** [comment]
@Lanchon Can you test a dumpling 15.1 build? It should work, just to be extra sure. If so, send me an email to nicola@corna.info

**Comment by Lanchon** [comment]
great news! absolutely, i can test. emailing...

**Comment by ArchangeGabriel** [comment]
https://github.com/lineageos4microg/l4m_website/issues/13
