### ISSUE TITLE
LineageOS 15.1 builds for hammerhead

### ISSUE THREAD

**Issue by aminb** [lineageos4microg/l4m_website#17]
It would be great if you could enable LOS 15.1 builds for hammerhead (Nexus 5). There are two [unofficial](https://forum.xda-developers.com/google-nexus-5/development/unofficial-lineageos-15-1-t3741481) [builds](https://forum.xda-developers.com/google-nexus-5/development/rom-lineageos-15-1-nexus-5-t3756643) on XDA but as far as I know none of them support signature spoofing out of the box.

**Comment by corna** [comment]
We don't ship unofficial forks, sorry, you'll have to wait for the official LOS 15.1 release for hammerhead (or [uild LineageOS for microG by yourself](https://github.com/lineageos4microg/docker-lineage-cicd#build-for-dumpling-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid)).
