### ISSUE TITLE
No new updates for Mido

### ISSUE THREAD

**Issue by marlid91** [lineageos4microg/l4m_website#19]
I downloaded microg for Lineage OS at lineage.microg.com for Xiaomi Redmi Note 4. The latest update that I've gotten is from March 31st. There have been 2-3 updates for my phone since then, but I haven't received any. 

What's causing this problem?

**Comment by ArchangeGabriel** [comment]
As precised in https://github.com/microg/android_packages_apps_GmsCore/issues/523, there have been 2 updates for this phone upstream, but none of them appeared at https://download.lineage.microg.org/mido/.

**Comment by corna** [comment]
The build server was down some days during this week, so the build scheduled for the 7th was skipped, the next build should be done tomorrow. I don't know why they've shipped a build on 11th upstream, builds for mido are done on Saturday.

**Comment by ArchangeGabriel** [comment]
Likely to disable the April Fool.

**Comment by marlid91** [comment]
I received this week's update today.
