### ISSUE TITLE
mako 15.1 jars do not appear to be signed

### ISSUE THREAD

**Issue by rlbdv** [lineageos4microg/l4m_website#21]
e.g. from https://download.lineage.microg.org/mako/

```sh
$ keytool -list -printcert -jarfile lineage-15.1-20180604-microG-mako.zip
Not a signed jar file
```

but the 14.1 image is signed:

```sh
$ keytool -list -printcert -jarfile lineage-14.1-20180427-microG-mako.zip
Signer #1:
...
```

But the 14.1 image there, `https://download.lineage.microg.org/mako/lineage-14.1-20180427-microG-mako.zip` is signed.

**Comment by corna** [comment]
Duplicate of lineageos4microg/docker-lineage-cicd#4

**Comment by dontub** [comment]
IMHO this should be reopened since the website has to be updated to explain how to verify the new signature format.

**Comment by rugk** [comment]
This seems to be tracked in https://github.com/lineageos4microg/l4m_website/issues/58 now.
