### ISSUE TITLE
Link to this website from main

### ISSUE THREAD

**Issue by realmain** [lineageos4microg/l4m_website#3]
Currently, there is nowhere on [microG Project website](https://microg.org/) that links to the [LineageOS Fork page](https://lineage.microg.org/). There should probably be a link on the top bar next to **Download** saying **LineageOS** or somewhere.

**Comment by ArchangeGabriel** [comment]
Yes! While I’ve been following μG for more than a year, I’ve discovered LineageOS build only very recently.

**Comment by corna** [comment]
It's linked in the [Signature Spoofing page](https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing) (but the step "Must be enabled..." is unnecessary). This ROM is still young, in the future we will add some references on the main website.
