### ISSUE TITLE
no more weekly updates for d855 lineageOS despite new nightlies on lineageOS

### ISSUE THREAD

**Issue by tokariu** [lineageos4microg/l4m_website#31]
As the title says: for the LG D855 (and maybe others?) there is no automatically build microg version anymore. But at the L.OS website there are new nightly builds available. I know it's only being build once a week.. but now it's like the second or third week in a row without any updates. 

Seems like the automatically building process is hanging?

**Comment by tokariu** [comment]
all of a sudden "lineage-15.1-20190606-microG-d855.zip" is available now. last weeks update was missing, though.

**Comment by corna** [comment]
We have migrated the build and webserver to a new provider, which is the reason why in the last couple of weeks no new builds have been performed.

**Comment by TjrGithub** [comment]
The Mido build for 20190522 is still missing:
https://download.lineage.microg.org/mido/
https://download.lineageos.org/mido
