### ISSUE TITLE
request: add https://github.com/WeAreFairphone/flashable-zip_microG

### ISSUE THREAD

**Issue by zaoqi** [lineageos4microg/l4m_website#33]

**Comment by corna** [comment]
microG is already present in LineageOS for microG, what should be the purpose of flashable-zip_microG in this project?

**Comment by zaoqi** [comment]
for unofficial images

**Comment by corna** [comment]
We could already build for unofficial images with our current infrastructure, however at the moment we don't have the capacity to do so.
