### ISSUE TITLE
Weekly Builds for tissot (Xiaomi A1) aren't updated properly

### ISSUE THREAD

**Issue by mrbulang** [lineageos4microg/l4m_website#37]
lineage for microg link:
https://download.lineage.microg.org/tissot/

its matching lineageos link:
https://download.lineageos.org/tissot

the current microg build (lineageos 16) is stuck on 2019/7/24 build.
please help to fix it, thanks!

**Comment by corna** [comment]
Duplicate lineageos4microg/android_prebuilts_prebuiltapks#19.
