### ISSUE TITLE
Nasty bug in last polaris build - can you pull the binaries?

### ISSUE THREAD

**Issue by giorgiga** [lineageos4microg/l4m_website#39]
The latest build for Mi Mix 2S (lineage-16.0-20191107-microG-polaris.zip) has a bug where the phone will not wake up and needs to be power-cycled.

The bug is a Lineage one – see https://gitlab.com/LineageOS/issues/android/issues/1381

Since the bug is no nasty, is it be possible to delete the build so that people don't upgrade to it?

**Comment by corna** [comment]
Done, thanks for the report
