### ISSUE TITLE
Publish SHA-256 hashes of binaries

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/l4m_website#4]
It would be nice of you to not only publish MD5, but also the SHA-256 hashes of the binaries.

You may say MD5 should only be used to check for corruption of the files. And SHA-256 is okay, but once your server is compromised, it does not help. So you may encourage users to verify the integrated signatures.

But there is a valid need: If one wants to verify the binaries by downloading them over a second, different channel, the SHA-256 sum is handy, as you do not have to download the whole file.

**Comment by corna** [comment]
I am going to add the SHA256 anyways, but I don't understand your reasons: why can't you just obtain the key fingerprint from the two channels and check if those matches?

**Comment by rugk** [comment]
Ah, that's also a good idea, but not sure yet whether these fingerprints also are not just SHA-1 hashes, which would be weak/[should not be used](https://shattered.it/).

**Comment by corna** [comment]
See [here](https://lineage.microg.org/#instructions), we also publish SHA-256 fingerprints

**Comment by rugk** [comment]
Okay, great. Still does not hurt to publish SHA-256 hashes of downloads… Upstream does it too.

**Comment by corna** [comment]
Done in lineageos4microg/docker-lineage-cicd@4176346648ec1af491962552b9cd236cb271128c, will appear in the next days on the download pages.
