### ISSUE TITLE
Failed builds since January, Moto X4 aka Payton

### ISSUE THREAD

**Issue by TobeStokes** [lineageos4microg/l4m_website#43]
No new builds for Payton have posted since January 30th.  Issue has been posted here, also to the microG reddit page, and to the XDA Developers thread on LineageOS for MicroG.  

I attempted to build my own update for payton using the Docker cicd image.  https://github.com/lineageos4microg/docker-lineage-cicd

**EDIT**
My builds failed initially but started working after I deleted all my downloads and build artifacts and started fresh, using the Docker method.   After migrating keys to my own generated keys and installing my build the phone is updated.  Yet no updates have posted since Jan 30th to the official LOS for MicroG website still on 3/21/20.

**Comment by ldoolitt** [comment]
Thanks for your valiant attempt!  You got further than I did.  My main handicap is that I have no trust in Docker, so I'm running in a chroot and reverse-engineering the scripts as I go.  Plus, my download speed is slow and capped.

**Comment by hhoefener** [comment]
Did you have a look into the log files? They are in the folder you mounted to /srv/logs.

**Comment by TobeStokes** [comment]
> Did you have a look into the log files? They are in the folder you mounted to /srv/logs.

Nope, I didn't even realize they were there.  Found some more info in the build log, seems like it thinks it's missing the proprietary vendor files even though the Muppets repo is in the manifests already.   


`device/motorola/sdm660-common/common.mk:396: error: _nic.PRODUCTS[[device/motorola/payton/lineage_payton.mk]]:"vendor/motorola/sdm660-common/sdm660-common-vendor.mk" does not exist.  dumpvars failed with: exit status 1`

`** Don't have a product spec for: 'lineage_payton'
** Do you have the right repo manifest?`

**Comment by hhoefener** [comment]
Would be interesting to know what settings are used to create the official L4M builds. Do they use the TheMuppets option?

**Comment by ldoolitt** [comment]
I see TheMuppets repo has a file proprietary_vendor_motorola/sdm660-common/sdm660-common-vendor.mk, even in their lineage-16.0 branch.
Guessing that TheMuppets is installed as the vendor directory, maybe device/motorola/sdm660-common/common.mk:390 needs to be patched to refer to proprietary_vendor_motorola instead of just motorola?
Just guessing, since I haven't found the source of device/motorola/sdm660-common/common.mk yet.

**Comment by TobeStokes** [comment]
Slight error in my log entry posted before, it was common.mk:402 instead of 396 - copied that from a different page from google searching the error.  Otherwise it was right though.  

Correct error (oxymoron?) here:

`device/motorola/sdm660-common/common.mk:402: error: _nic.PRODUCTS[[device/motorola/payton/lineage_payton.mk]]:"vendor/motorola/sdm660-common/sdm660-common-vendor.mk" does not exist. 
04:03:57 dumpvars failed with: exit status 1
device/motorola/sdm660-common/common.mk:402: error: _nic.PRODUCTS[[device/motorola/payton/lineage_payton.mk]]:"vendor/motorola/sdm660-common/sdm660-common-vendor.mk" does not exist. 
04:04:00 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_payton' 
** Do you have the right repo manifest?`

**Comment by TobeStokes** [comment]
> Would be interesting to know what settings are used to create the official L4M builds. Do they use the TheMuppets option?

I don't know where they get the proprietary files for the builds posted to lineageos.org but in their official build guides they instruct you to use a process to pull the files from your phone directly over USB, I think for legal liability issues or whatnot.  They don't overtly use Muppets repo at least.

**Comment by wismann83** [comment]
Yesterday I tried, unaware of this thread, making a local build and it succeeded. When I get home I could post the docker invocation settings if someone's interested. The command line has been taken from the build tutorial, so nothing out of the ordinary.

**Comment by TobeStokes** [comment]
> Yesterday I tried, unaware of this thread, making a local build and it succeeded. When I get home I could post the docker invocation settings if someone's interested. The command line has been taken from the build tutorial, so nothing out of the ordinary.

Yes, please post your docker setup info and I'll probably try another run this evening after work (CDT zone here).  I'm wondering maybe if there was a problem in the source code that got fixed or something, since you mentioned using the tutorial commands and that's how I ran mine too.  

Also if you recall how long the build process took to complete that would be interesting to know.  Last time I built lineageOS successfully it was a standard non docker / microg build and I think it was 6 to 8 hours after all the code downloading part, the actual building time.

**Comment by omgwtfbbqpls** [comment]
For us plebs who don't know how to use Docker, what can we do at this point?

**Comment by wismann83** [comment]
>Yes, please post your docker setup info 

```
docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=payton" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v [...] \
    lineageos4microg/docker-lineage-cicd
```

I excluded the file mapping (`-v [...]`). For this, I modified the example for lineageos 15.1 for angler [(url)](https://github.com/lineageos4microg/docker-lineage-cicd#build-for-angler-lineage-151-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid). As others have stated, I also do not know what configuration the official server uses.

>Also if you recall how long the build process took to complete that would be interesting to know.
>[...]I think it was 6 to 8 hours[...]

Yes, maybe a little bit faster. Running on a Thinkpad X240 i7, source code folder on external USB (running out of built in SSD storage), so a less than ideal build setup.

> For us plebs who don't know how to use Docker, what can we do at this point?

Firstly, building with docker is so easy.
1. You go through the docker tutorial for your OS until you can run the hello-world container
2. You read the tutorial on docker-lineage-cicd options
3. You decide where the local storage folders should be (build needs around 250GB - 300GB local storage)

Secondly, this depends on what you mean by what you can do.
I never intended to use the build on my phone. I just wanted to see whether a local build would succeed. As I stated in my first post, I didn't know whether other folks tried building locally.
There might be caveats or even problems when using a local build on top of an official build due to different keys. I'm a long time lineageos user, but I'm a total noob building android images.

**Comment by TobeStokes** [comment]
Thanks for the info wissman83.  My docker run command was no different than yours essentially.  

I went ahead and ran it again, and it failed again, but after taking longer to download more stuff than the last few tries.  I'm sure there were a few changes in the time that has elapsed.  

Next I guess I will start deleting stuff and make it re-download more of it or all of it to start more fresh.  Going to try deleting stuff from the directories mentioned in this error first to try to save some download time....   

`device/motorola/sdm660-common/common.mk:402: error: _nic.PRODUCTS.[[device/motorola/payton/lineage_payton.mk]]: "vendor/motorola/sdm660-commo$
00:28:06 dumpvars failed with: exit status 1
device/motorola/sdm660-common/common.mk:402: error: _nic.PRODUCTS.[[device/motorola/payton/lineage_payton.mk]]: "vendor/motorola/sdm660-commo$
00:28:09 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_payton'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
>> [Tue Mar 17 00:28:09 UTC 2020] Failed build for payton
>> [Tue Mar 17 00:28:09 UTC 2020] Finishing build for payton
>> [Tue Mar 17 00:28:09 UTC 2020] Cleaning source dir for device payton
00:28:10 Entire build directory removed.
`

**Comment by TobeStokes** [comment]
OK I finally got my build to build.  Used the default docker command and it worked, just as I did when it didn't work before.  
I had to delete all my downloaded stuff and start from scratch, and expand my VM hard drive to 300GB ( think it only needed about 250GB but not sure).  It took about 5 hours to build after all the source code was synced, on a 6-core desktop with 16GB ram and SSD.  

I learned that VirtualBox is really stupid with handling expansion of dynamically-allocated VHDs along the way.  It just kept getting bigger and bigger, and I ended up with 500GB space used for a 300GB Linux drive, with only 158GB in use by Linux after the build was complete.  Might be better just to make a fixed-size 250GB one next time and start totally from scratch.  

Next I'm going to make some backups of my phone and attempt to install my creation.  I'm done waiting for the unresponsive LOS for MicroG people here to address the lack of updates.  

Info about migrating your phone from an Official build to Unofficial (or self-built) is available here in the section titled "Using a script" - https://wiki.lineageos.org/signing_builds.html
I guess I'm going to try that.
The migration.sh script it mentions is not in the same place for this Docker build, but I found it here:
/home/user/lineage/LINEAGE_16_0/lineage/scripts/key-migration/

**Comment by TobeStokes** [comment]
March 21st is here, still no new builds up for Moto X4 here:  https://download.lineage.microg.org/payton/

Last build was January 30th.  Docker build is verified to work.  I wonder what the issue with the website is?

**Comment by Egocentrix** [comment]
I just found this thread looking for news on the X4 updates. So do I understand correctly that docker builds work on some machines but not others? That's ironic.

I might try to build myself an up to date L4M, but using the official build would of course be better.

Why on earth does a build require 200GB of space anyway, that is ridiculously large...

**Comment by TobeStokes** [comment]
> I just found this thread looking for news on the X4 updates. So do I understand correctly that docker builds work on some machines but not others? That's ironic.
> 
> I might try to build myself an up to date L4M, but using the official build would of course be better.
> 
> Why on earth does a build require 200GB of space anyway, that is ridiculously large...

I got the docker build to work on a plain standard Ubuntu VM, using the docker build instructions posted by the official LineageOS for MicroG site.  I still don't know why my initial attempts failed, but I did learn that you need to start with 250+ GB of storage available.  yes that is a lot, and I don't know why it needs so much vs standard LineageOS which only needs 100 to 120.  Anyway, it's pretty easy to do, install docker on Linux and run the build command, then wait for many hours.  

The most complex part (other than troubleshooting my initial failures) was changing the signing keys to use my own keys instead of the official release keys.  This is necessary if you build your own, and you can either use the "test keys" or make your own keys automatically during the build.  But even though that was a bit complex, careful reading and following the instructions allowed me to succeed at it.  I guess I'll keep making my own builds if they don't resume providing updates here...

**Comment by Tyler-2** [comment]
Just replying to confirm I too am suffering from the lack of update!

**Comment by Tyler-2** [comment]
I think this should be marked as a duplicate of https://github.com/lineageos4microg/l4m_website/issues/41

**Comment by jw243** [comment]
I wonder whether this issue will ever be solved. Will there be any updates for payton in the future? It's now been 4 months since the last update. Really sad...

**Comment by TobeStokes** [comment]
If anyone wants an updated build of LineageOS for MicroG (16.0 not 17.1) for Moto X4 I have uploaded a test keys build here:

https://www.androidfilehost.com/?w=files&flid=312805

**Comment by omgwtfbbqpls** [comment]
> 
> 
> If anyone wants an updated build of LineageOS for MicroG (16.0 not 17.1) for Moto X4 I have uploaded a test keys build here:
> 
> https://www.androidfilehost.com/?w=files&flid=312805
> 
> This is a 5/23/20 build with May 2020 security patch level.

Thank you, many will probably find it useful (though I personally wouldn't install it out of worry of bricking my only phone). 

Can someone get in touch with whoever is in charge of this project, and have them do whatever you did so that we can start getting it officially again?

**Comment by ArchangeGabriel** [comment]
@omgwtfbbqpls I’ve tried to reach @corna by email, but without results for now…

**Comment by omgwtfbbqpls** [comment]
> @omgwtfbbqpls I’ve tried to reach @corna by email, but without results for now…

I imagine that if someone messaged "Hey, someone finally figured out how to fix this issue and all you need to do is quickly implement it" he or someone else might be willing to do it. Assuming it really is that simple to fix now, though.

**Comment by TobeStokes** [comment]
> I imagine that if we start messaging "Hey, someone finally figured out how to fix this issue and all you need to do is quickly implement it" he or someone else might be willing to do it. Assuming it really is that simple to fix now, though.

Honestly I didn't really figure anything significant out about "fixing" the build process.  I think initially I had some corrupted downloads of the source code or something, because all I did to make it work was to delete everything and start over.  

I think the issue with no new builds being uploaded is that their system is either hung up, stopped, or broken somehow.  And it seems that no one is paying attention to it or working on that part of the LineageOS for MicroG project.  I could be wrong, that's just what it looks like to me after building my own build easily using their instructions and no official responses to this issue.

But I can't complain too much, at least they used to provide builds for us for free, and their instructions to make new builds still work.  

Currently I'm trying to figure out how to get the updated proprietary drivers / blobs (whatever they are) extracted into my build process to get a more completely updated system, since the proprietary stuff that the docker builds pull from The Muppets repo is over a year outdated - vendor security patches on docker builds show March 2019 date.  I got another Moto X4 on ebay for cheap and updated it all the way with Motorola OEM software, and it got security patches all the way up to March 2020, so hopefully I can end up with a payton build that has May 2020 AOSP patch and March 2020 Motorola patches.  Unfortunately my first run last weekend gave me a build with the LTE data not working, so I screwed something up.

**Comment by Egocentrix** [comment]
Given that the build image is proven to work, the problem must be the config on their server. Just taking a wild guess it could be that size is an issue. A regular LOS build takes around 100GB of space, and apparently including MicroG increases that to a whopping 250! Could be that the build server is just not prepared for that. Maybe the 250GB is not normal and there is a config issue for payton that it requires that much space.

**Comment by wismann** [comment]
> Currently I'm trying to figure out how to get the updated proprietary drivers / blobs (whatever they are) extracted into my build process to get a more completely updated system, since the proprietary stuff that the docker builds pull from The Muppets repo is over a year outdated - vendor security patches on docker builds show March 2019 date. I got another Moto X4 on ebay for cheap and updated it all the way with Motorola OEM software, and it got security patches all the way up to March 2020, so hopefully I can end up with a payton build that has May 2020 AOSP patch and March 2020 Motorola patches. Unfortunately my first run last weekend gave me a build with the LTE data not working, so I screwed something up.

To me, this sounds like your're making modifications to the original Dockerfile. Would you mind providing your fork in github?

**Comment by TobeStokes** [comment]
> > Currently I'm trying to figure out how to get the updated proprietary drivers / blobs (whatever they are) extracted into my build process to get a more completely updated system, since the proprietary stuff that the docker builds pull from The Muppets repo is over a year outdated - vendor security patches on docker builds show March 2019 date. I got another Moto X4 on ebay for cheap and updated it all the way with Motorola OEM software, and it got security patches all the way up to March 2020, so hopefully I can end up with a payton build that has May 2020 AOSP patch and March 2020 Motorola patches. Unfortunately my first run last weekend gave me a build with the LTE data not working, so I screwed something up.
> 
> To me, this sounds like your're making modifications to the original Dockerfile. Would you mind providing your fork in github?

No I didn't change the docker stuff, I was just mixing methods between the standard manual LineageOS build and the docker automated way.  They both pretty much do the same stuff (as far as I can tell) with the exception of the docker way having the options to integrate signature spoofing, MicroG, etc.

What I did modify was the source code files that the docker build retrieves during its process.  Part of that stuff includes an "extract-files.sh" script that the manual build method uses to pull vendor files from a running phone.  I ran that script on my newly OEM-updated Moto X4 to get the newer vendor files.  But I think I either ended up with them not in the right spots in the build folder, or the build just has some problems related to their inclusion because my LTE didn't work.  Ended up having to revert to my 5/23 build that I posted links to, to get my LTE back.

**Comment by Tyler-2** [comment]
Basically this is all bad news for someone who doesn't have much
understanding of Android, and just wants LOS+MicroG for the sake of
de-googling their phone.

**Comment by omgwtfbbqpls** [comment]
Does this have anything to do with the delays the creator of MicroG has had?

https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344

**Comment by ArchangeGabriel** [comment]
> Does this have anything to do with the delays that the creator of MicroG has had?
> 
> https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344
> 
> Will updates resume once our benevolent dictator returns?

No, @mar-v-in is not implicated in lineageos4microg. @corna is, but currently busy with other things and not sure if/when he will be able to resume work here.

**Comment by omgwtfbbqpls** [comment]
Apparently _Official LOS 16_ for Moto X4 isn't receiving more updates because the [Moto X4 has been promoted to _LOS 17.1._](https://www.reddit.com/r/LineageOS/comments/h00ih8/the_moto_g4_play_moto_x_play_moto_g3_turbo_moto_g/ftkvamp/)

It's still possible (but difficult) for someone to [make _LOS 16_ builds themselves though,](https://www.reddit.com/r/LineageOS/comments/h00ih8/the_moto_g4_play_moto_x_play_moto_g3_turbo_moto_g/fukqneb/) they just aren't doing it officially because of limited resources. 

But is this the reason _LOS 16 for MicroG_ for Moto X4 hasn't been updated? I don't know if _LOS 16 for MicroG_ builds are based on the official releases or if they're built independently.

**Comment by Tyler-2** [comment]
Is it likely that we'll have MicroG / LOS 17.1 builds soon? Is there a direct upgrade path? I'm curious what more knowledgeable X4 users are doing.

**Comment by omgwtfbbqpls** [comment]
> @Tyler-2 Is it likely that we'll have MicroG / LOS 17.1 builds soon? Is there a direct upgrade path? I'm curious what more knowledgeable X4 users are doing.

I (and probably others) would also want to have support for LOS 16, though.

**Comment by TobeStokes** [comment]
I don't know anything about the status of builds either at this point, but there has been some recent progress on the MicroG project itself, so it's possible that builds of LOS4MicroG might resume at some future point.  
I'm still running my own builds as I mentioned before, using the docker build method.  I wasn't able to figure out how to get the newer OEM files from Motorola's OEM ROM to work, and I ended up just having to wipe everything in my build directories again to make a normal build work again.  

For news about MicroG, there seems to be some activity on the MicroG subreddit here:  

> https://old.reddit.com/r/MicroG/

> https://old.reddit.com/r/MicroG/comments/hv80sv/no_new_updates_for_lineage_with_microg_for_a_few/

> https://old.reddit.com/r/MicroG/comments/hvr58t/microg_for_lineage_171/

> https://old.reddit.com/r/MicroG/comments/hyfoil/microg_update_out/

**Comment by TobeStokes** [comment]
Welp, there's a new build out there on the LineageOS for MicroG website, so I guess I'll close this issue.  

It's a LineageOS 17.1 build, which is nice for those who want the new version.  For now I'm going to stick with my own builds of LOS 16 with MicroG but I may give this new build a try on my spare Moto X4.  

Thanks to everyone who has contributed to LineageOS and MicroG and LineageOS for MicroG.
