### ISSUE TITLE
Update microG release

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/l4m_website#50]
There is a new microG release, so it would be good to update it here too! :smiley: 

https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.11.202414

v0.2.11.202414

Pay attention to the notes there:
> Notes:
> *   It may be required to re-enable UnifiedNlp location modules
> *    Make sure Self-Check is all good after upgrade

**Comment by bananer** [comment]
https://github.com/lineageos4microg/android_prebuilts_prebuiltapks
