### ISSUE TITLE
Updates for cheeseburger, dumpling (OnePlus 5, 5T)

### ISSUE THREAD

**Issue by xPMo** [lineageos4microg/l4m_website#61]
LineageOS is releasing LineageOS 17.1 for these two devices. Currently [the dumpling build is up](https://download.lineageos.org/dumpling), but [not on l4m](https://download.lineage.microg.org/dumpling).

I have noticed other open update requests in the issue tracker here. If builds are not happening automatically, perhaps a way to get in touch with the maintainers to ask for new builds is necessary? This repository does not seem like the ideal place to report upstream updates to LOS, but [the bug-reporting flowchart directs here](https://lineage.microg.org/images/bug_reporting.svg).

**Comment by leo-lb** [comment]
They are available now, this can be closed!

**Comment by xPMo** [comment]
Thanks for letting me know!
