### ISSUE TITLE
Suggestion for slower update cycle

### ISSUE THREAD

**Issue by bitpixl** [lineageos4microg/l4m_website#72]
Hi,

fist off all I really don't mind the slower update cycle, but I would really prefer to receive an update as soon stock lineageos releases an update with the latest security patches. Hopefully this is in some way manageable.

Keep up the great work!

**Comment by bananer** [comment]
Trying to keep all current discussion around build frequency here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/166
