### ISSUE TITLE
Why weekly release LOS 18.1 for bacon stopped ?!

### ISSUE THREAD

**Issue by hamedsbt** [lineageos4microg/l4m_website#74]
As official LOS 18.1 page: **https://www.lineageoslog.com/18.1/bacon** there are tow major releases 2021-**04-15** and 2021-**04-22** but they are not exist on: https://download.lineage.microg.org/bacon

Update microg built-in please!

**Comment by ArchangeGabriel** [comment]
LOS4mG does not have the same building power, builds are roughly monthly.

**Comment by bananer** [comment]
Trying to keep all current discussion around build frequency here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/166
