### ISSUE TITLE
Hash Check Failed--kltedv

### ISSUE THREAD

**Issue by boggle247** [lineageos4microg/l4m_website#8]
Regarding the Lineage-14.1-20171213-microG-kltedv.zip (last modified 2017-12-13 01:14).  

I've never checked a hash before but I did it using HashStamp from the playstore. I opened the downloaded zip file and clicked generate and neither the MD5 nor the SHA-1 values math those found on the lineage.microg.org values. Nor does the inlcuded MD5SUM file match the zip or the values on the website. Maybe I'm doing this wrong....

Edit: I also downloaded the zip to windows and used HashCalc (slavasoft.com) and got the results in the image:

![image](https://user-images.githubusercontent.com/32688058/33951648-8a474aae-dffd-11e7-835e-0afeb5f72689.png)

 From the lineage.microg.com site:

![image](https://user-images.githubusercontent.com/32688058/33951673-9d88a1da-dffd-11e7-99b7-4c910236a212.png)

**Comment by corna** [comment]
You're comparing two different hashes:
 * the first ones are the hashes of the ZIP file, useful to quickly check if the download has been **accidentally** corrupted: you can compare the MD5 sum (and soon the SHA256) you've locally computed with [the one stored in the website](https://download.lineage.microg.org/kltedv/lineage-14.1-20171213-microG-kltedv.zip.md5sum); as you can see, it matches
 * the second ones are the hashes of the public key used to sign each build and can be used to make sure that the downloaded ZIP is authentic: if the verification process succeeds and the fingerprint matches, you're sure that no one has tampered your ZIP

**Comment by boggle247** [comment]
@corna Okay thanks. But the MD5 file stored on the website that you linked (shown below) and the hash generated from the zip file don't match either..

![image](https://user-images.githubusercontent.com/32688058/33953246-5a5f13f8-e002-11e7-8ce9-3da096822b63.png)


How do I check the fingerprint of the zip with the public key on there site? I'm sorry if this is the wrong place, but I can't find a forum that discuss's MicroG and LineageOS. The LOS subreddit absolutely prohibits the mention of microG.

**Comment by corna** [comment]
You don't have to compute the hash of the *.md5sum file: it's a text file, open it and check that it matches with the one you generated first (or use a program that checks it for you). The process to verify the fingerprint is just above the fingerprints you've copied from the website:

     keytool -list -printcert -jarfile lineage-microG.zip

That's a command for Linux/MacOS, if you use Windows the command should be something like

     C:\Program Files\<path to Java>\bin\keytool.exe -list -printcert -jarfile <path to the downloaded zip>\lineage-microG.zip

to be run in a `cmd.exe`.

**Comment by corna** [comment]
By the way, this process is identical to the [LineageOS' one](https://wiki.lineageos.org/verifying-builds.html), the only differences are the key fingerprints (as we sign with different keys).

**Comment by boggle247** [comment]
OHH okay. Well it is indeed correct. Thanks for teaching me that. I will only add (for others reference) that in windows you are correct except you need quotes around the program path for the java keytool: 

` "C:\Program Files\<path to Java>\bin\keytool.exe" -list -printcert -jarfile <path to the downloaded zip>\lineage-microG.zip`

No quotes around teh path to the zip. 

Thanks again for all your help.
