### ISSUE TITLE
Doesn't tell to wipe System

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [lineageos4microg/l4m_website#9]
Hi :)

I had an issue installing LOS+MG and I was told to report it here.

Here's the link to the issue I had filed : https://github.com/microg/android_packages_apps_GmsCore/issues/465

So I think it was the correct place to report it :)

**Comment by ale5000-git** [comment]
One additional improvements would also to auto-ignore the script in /system/addon.d/ added from the Open GApps zip.

**Comment by corna** [comment]
Updated, thank you.

@ale5000-git there might be other scripts there: a full wipe of _System_ is recommended.

**Comment by ale5000-git** [comment]
@corna: Yes, but ignoring the script used by OpenGapps (very common) doesn't cause any problem and often is the only one causing problems.

**Comment by corna** [comment]
I'll have a look

**Comment by Lanchon** [comment]
wow, @corna of ME cleaner fame is on the l4m team! awesome, thanks!
